---
- apt_key:
    url: "https://developer.download.nvidia.com/compute/cuda/repos/{{ nvidia_repo_distarch }}/7fa2af80.pub"
    id: 7fa2af80
    state: present

- apt_repository:
    repo: 'deb http://developer.download.nvidia.com/compute/cuda/repos/{{ nvidia_repo_distarch }} /'
    state: present
    filename: cuda
  register: nvidia_repo_cuda_apt_repo

- name: install cuda drivers
  apt:
    name: cuda-runtime-{{cuda_version}}
    update_cache: yes
    allow_unauthenticated: yes
    state: present